name: Build Typst Documents

on:
    push:
        paths:
            - "**.typ"
            - ".github/workflows/typst-compile.yaml"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: prepare Install fonts
              uses: fontist/setup-fontist@v2
            - name: Install fonts
              run: |
                  fontist install "Inter"
                  fontist install "firamath"
            - name: Install Typst
              uses: typst-community/setup-typst@v4
            - name: Compile Typst documents
              run: |
                  mkdir -p build
                  for file in $(find . -name "*.typ"); do
                    name=$(basename "$file" .typ)
                    typst compile --font-path ~/.fontist/fonts "$file" "build/$name.pdf"
                  done

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: latest
                  name: latest version of the notes
                  body: Automatically generated PDFs from the latest commit.
                  files: build/*.pdf
                  prerelease: true
                  make_latest: true
              # env:
              #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
