name: Build Typst Documents

on:
    push:
        paths:
            - "**.typ"
            - ".github/workflows/typst-compile.yaml"
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: prepare Install fonts
              uses: fontist/setup-fontist@v2
            - name: Install fonts
              run: |
                  fontist install "Inter"
                  fontist install "firamath"
            - name: Install Typst
              uses: typst-community/setup-typst@v4
            - name: Compile Typst documents
              run: |
                  mkdir -p build
                  for file in $(find . -name "*.typ"); do
                    name=$(basename "$file" .typ)
                    typst compile "$file" "build/$name.pdf"
                  done

            - name: Upload PDFs
              uses: actions/upload-artifact@v4
              with:
                  name: typst-pdfs
                  path: build/*.pdf
